version: '3.7'

services:
  web:
    build: ./app
    command: pipenv run flask run --host 0.0.0.0 --port $APP_PORT
    env_file: ./app/.env
    restart: always
    ports:
      - 8080:${APP_PORT}
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - postgres
  postgres:
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432

volumes:
  postgres_data:
