version: '3.7'

services:
  web:
    build: ./app
    env_file: ./app/.env
    restart: always
    ports:
      - 8080:${APP_PORT}
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - postgres
  postgres:
    image: postgres:12.0-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:5432
    redis:
      image: redis:alpine
      command: redis-server
      restart: unless-stopped
      ports:
        - ${REDIS_PORT}:6379
      environment:
        - REDIS_REPLICATION_MODE=master

volumes:
  postgres_data:
